### ISSUE TITLE
train

### ISSUE THREAD

**Issue by lixiang4659** [YQ-097/MPCFusion#2]
请问您八千多张图片在3070上训练，需要训练多久

**Comment by YQ-097** [comment]
看训练轮数吧，MPCFusion的训练应该十个小时左右（距离做实验的时候快一年了，可能有点偏差哈）

**Comment by lixiang4659** [comment]
那您的数据集还存着吗，KAIST数据集太大了，我这边下载有点困难，如果有的话，可以发我一份吗，感谢    
这是我的邮箱：1395665231@qq.com

**Comment by YQ-097** [comment]
这个数据集做训练我觉得并不理想，建议你可以使用其他数据集。这是我使用的KAIST数据集链接：https://pan.baidu.com/s/1JFXm61mCOy599xxCBNkkAg?pwd=suep 提取码：suep
